version: '2'
services:
  lernprogramm-postgresql:
    image: 17031962/lernplattform:dbtest
    # volumes:
    #     - ~/volumes/jhipster/lernprogramm/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=lernprogramm
      - POSTGRES_PASSWORD=
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - 5432:5432
